apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: demo-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-k8s
      app.kubernetes.io/instance: demo-k8s
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-k8s
        app.kubernetes.io/instance: demo-k8s
    spec:
      containers:
      - name: demo-k8s-container
        image: axelsantoro/prueba-docker:1.0.0
        env:
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /demo
        backend:
          serviceName: kubernetes
          servicePort: 80